### ISSUE TITLE
idea: make truncate length configurable

### ISSUE THREAD

**Issue by cord** [Sommerregen/grav-plugin-toc#4]
would be great to be able to configure the truncate length

**Comment by Sommerregen** [comment]
Hi @cord,

you are right. Currently the truncate length is hardcoded (FYI https://github.com/Sommerregen/grav-plugin-toc/blob/master/classes/Toc.php#L437). It is ok for you, if the truncate length is added as an option to the `toc.yaml` and Admin panel?

**Comment by cord** [comment]
> It is ok for you, if the truncate length is added as an option to the toc.yaml 

yes for sure :)

**Comment by Sommerregen** [comment]
I have added some options concerning slug generation and your forums request. Instead of implementing a filter technique (with black- and whitelist I decided to stick to a simple option `process`).

``` yaml
slug:                        # Slug generation
  truncate: true             # Truncate headings for slug generation
  length: 32                 # Slug string length
  break: "-"                 # The break delimiter to divide the slug into pieces of words.
  pad: "-..."                # Added to the end of the truncated slug

process: true                # Process table of contents
```

 In your case just set `process: false` and use `{{ page.content|toc }}` in your Twig files. Twig filter is working again.
